### PR TITLE
Add CUDA simulator.

### PR DESCRIPTION
**Pull request by sergeisakov**

### CODE REVIEW

**Review by MichaelBroughton — COMMENTED** [review]
This looks good to me. I'll leave it to @95-martin-orion for final say. I don't think actions has GPU support so we might need to setup a new kokoro pipeline for the tests ? Are there any performance plots so we can know when the GPU starts to beat out the CPU ? I imagine at small-ish sizes the CPU would still win since it doesn't have to do any kernel launches or anything like that ?

**Comment by 95-martin-orion** [comment]
> I don't think actions has GPU support so we might need to setup a new kokoro pipeline for the tests ?

Yeah, this is tied to #363. I checked with the Google OSS team and they also recommended Kokoro - there's currently no Google-level support for doing this through Github Actions.

**Comment by 95-martin-orion** [comment]
@sergeisakov, do you have test logs for this that you can share? I don't think I can provide meaningful review above and beyond anything @MichaelBroughton has already done, but having logs from a passing test would increase my confidence in this PR.

**Comment by sergeisakov** [comment]
> Are there any performance plots so we can know when the GPU starts to beat out the CPU ? I imagine at small-ish sizes the CPU would still win since it doesn't have to do any kernel launches or anything like that ?

No, I don't have any performance plots. Nvidia V100 is 9 times faster than Intel Xeon Gold 6154 for 30-qubit circuits. You're right that the difference in performance gets smaller with decreasing the circuit size.

**Comment by sergeisakov** [comment]
> @sergeisakov, do you have test logs for this that you can share?

Here are the test logs (run on Nvidia Quadro P1000):

$ ./statespace_cuda_test.x
[==========] Running 25 tests from 3 test suites.
[----------] Global test environment set-up.
[----------] 11 tests from StateSpaceCUDATest/0, where TypeParam = float
[ RUN      ] StateSpaceCUDATest/0.Add
[       OK ] StateSpaceCUDATest/0.Add (137 ms)
[ RUN      ] StateSpaceCUDATest/0.NormSmall
[       OK ] StateSpaceCUDATest/0.NormSmall (3 ms)
[ RUN      ] StateSpaceCUDATest/0.NormAndInnerProductSmall
[       OK ] StateSpaceCUDATest/0.NormAndInnerProductSmall (2 ms)
[ RUN      ] StateSpaceCUDATest/0.NormAndInnerProduct
[       OK ] StateSpaceCUDATest/0.NormAndInnerProduct (73 ms)
[ RUN      ] StateSpaceCUDATest/0.SamplingSmall
[       OK ] StateSpaceCUDATest/0.SamplingSmall (4238 ms)
[ RUN      ] StateSpaceCUDATest/0.Ordering
[       OK ] StateSpaceCUDATest/0.Ordering (143 ms)
[ RUN      ] StateSpaceCUDATest/0.MeasurementLarge
[       OK ] StateSpaceCUDATest/0.MeasurementLarge (150 ms)
[ RUN      ] StateSpaceCUDATest/0.Collapse
[       OK ] StateSpaceCUDATest/0.Collapse (3620 ms)
[ RUN      ] StateSpaceCUDATest/0.BulkSetAmpl
[       OK ] StateSpaceCUDATest/0.BulkSetAmpl (6203 ms)
[ RUN      ] StateSpaceCUDATest/0.BulkSetAmplExclusion
[       OK ] StateSpaceCUDATest/0.BulkSetAmplExclusion (6190 ms)
[ RUN      ] StateSpaceCUDATest/0.BulkSetAmplDefault
[       OK ] StateSpaceCUDATest/0.BulkSetAmplDefault (2 ms)
[----------] 11 tests from StateSpaceCUDATest/0 (20761 ms total)

[----------] 11 tests from StateSpaceCUDATest/1, where TypeParam = double
[ RUN      ] StateSpaceCUDATest/1.Add
[       OK ] StateSpaceCUDATest/1.Add (2 ms)
[ RUN      ] StateSpaceCUDATest/1.NormSmall
[       OK ] StateSpaceCUDATest/1.NormSmall (3 ms)
[ RUN      ] StateSpaceCUDATest/1.NormAndInnerProductSmall
[       OK ] StateSpaceCUDATest/1.NormAndInnerProductSmall (2 ms)
[ RUN      ] StateSpaceCUDATest/1.NormAndInnerProduct
[       OK ] StateSpaceCUDATest/1.NormAndInnerProduct (186 ms)
[ RUN      ] StateSpaceCUDATest/1.SamplingSmall
[       OK ] StateSpaceCUDATest/1.SamplingSmall (4166 ms)
[ RUN      ] StateSpaceCUDATest/1.Ordering
[       OK ] StateSpaceCUDATest/1.Ordering (119 ms)
[ RUN      ] StateSpaceCUDATest/1.MeasurementLarge
[       OK ] StateSpaceCUDATest/1.MeasurementLarge (376 ms)
[ RUN      ] StateSpaceCUDATest/1.Collapse
[       OK ] StateSpaceCUDATest/1.Collapse (3522 ms)
[ RUN      ] StateSpaceCUDATest/1.BulkSetAmpl
[       OK ] StateSpaceCUDATest/1.BulkSetAmpl (5942 ms)
[ RUN      ] StateSpaceCUDATest/1.BulkSetAmplExclusion
[       OK ] StateSpaceCUDATest/1.BulkSetAmplExclusion (5937 ms)
[ RUN      ] StateSpaceCUDATest/1.BulkSetAmplDefault
[       OK ] StateSpaceCUDATest/1.BulkSetAmplDefault (1 ms)
[----------] 11 tests from StateSpaceCUDATest/1 (20256 ms total)

[----------] 3 tests from StateSpaceCUDATest
[ RUN      ] StateSpaceCUDATest.SamplingCrossEntropyDifference
[       OK ] StateSpaceCUDATest.SamplingCrossEntropyDifference (20885 ms)
[ RUN      ] StateSpaceCUDATest.MeasurementSmall
[       OK ] StateSpaceCUDATest.MeasurementSmall (73814 ms)
[ RUN      ] StateSpaceCUDATest.InvalidStateSize
[       OK ] StateSpaceCUDATest.InvalidStateSize (0 ms)
[----------] 3 tests from StateSpaceCUDATest (94699 ms total)

[----------] Global test environment tear-down
[==========] 25 tests from 3 test suites ran. (135716 ms total)
[  PASSED  ] 25 tests.



$ ./simulator_cuda_test.x
[==========] Running 19 tests from 3 test suites.
[----------] Global test environment set-up.
[----------] 9 tests from SimulatorCUDATest/0, where TypeParam = float
[ RUN      ] SimulatorCUDATest/0.ApplyGate1
[       OK ] SimulatorCUDATest/0.ApplyGate1 (137 ms)
[ RUN      ] SimulatorCUDATest/0.ApplyGate2
[       OK ] SimulatorCUDATest/0.ApplyGate2 (1 ms)
[ RUN      ] SimulatorCUDATest/0.ApplyGate3
[       OK ] SimulatorCUDATest/0.ApplyGate3 (2 ms)
[ RUN      ] SimulatorCUDATest/0.ApplyGate5
[       OK ] SimulatorCUDATest/0.ApplyGate5 (2 ms)
[ RUN      ] SimulatorCUDATest/0.CircuitWithControlledGates
[       OK ] SimulatorCUDATest/0.CircuitWithControlledGates (9 ms)
[ RUN      ] SimulatorCUDATest/0.CircuitWithControlledGatesDagger
[       OK ] SimulatorCUDATest/0.CircuitWithControlledGatesDagger (11 ms)
[ RUN      ] SimulatorCUDATest/0.MultiQubitGates
[       OK ] SimulatorCUDATest/0.MultiQubitGates (700 ms)
[ RUN      ] SimulatorCUDATest/0.ExpectationValue1
[       OK ] SimulatorCUDATest/0.ExpectationValue1 (9 ms)
[ RUN      ] SimulatorCUDATest/0.ExpectationValue2
[       OK ] SimulatorCUDATest/0.ExpectationValue2 (25 ms)
[----------] 9 tests from SimulatorCUDATest/0 (896 ms total)

[----------] 9 tests from SimulatorCUDATest/1, where TypeParam = double
[ RUN      ] SimulatorCUDATest/1.ApplyGate1
[       OK ] SimulatorCUDATest/1.ApplyGate1 (0 ms)
[ RUN      ] SimulatorCUDATest/1.ApplyGate2
[       OK ] SimulatorCUDATest/1.ApplyGate2 (1 ms)
[ RUN      ] SimulatorCUDATest/1.ApplyGate3
[       OK ] SimulatorCUDATest/1.ApplyGate3 (1 ms)
[ RUN      ] SimulatorCUDATest/1.ApplyGate5
[       OK ] SimulatorCUDATest/1.ApplyGate5 (3 ms)
[ RUN      ] SimulatorCUDATest/1.CircuitWithControlledGates
[       OK ] SimulatorCUDATest/1.CircuitWithControlledGates (9 ms)
[ RUN      ] SimulatorCUDATest/1.CircuitWithControlledGatesDagger
[       OK ] SimulatorCUDATest/1.CircuitWithControlledGatesDagger (12 ms)
[ RUN      ] SimulatorCUDATest/1.MultiQubitGates
[       OK ] SimulatorCUDATest/1.MultiQubitGates (751 ms)
[ RUN      ] SimulatorCUDATest/1.ExpectationValue1
[       OK ] SimulatorCUDATest/1.ExpectationValue1 (14 ms)
[ RUN      ] SimulatorCUDATest/1.ExpectationValue2
[       OK ] SimulatorCUDATest/1.ExpectationValue2 (64 ms)
[----------] 9 tests from SimulatorCUDATest/1 (855 ms total)

[----------] 1 test from SimulatorCUDATest
[ RUN      ] SimulatorCUDATest.ControlledGates
[       OK ] SimulatorCUDATest.ControlledGates (185250 ms)
[----------] 1 test from SimulatorCUDATest (185250 ms total)

[----------] Global test environment tear-down
[==========] 19 tests from 3 test suites ran. (187001 ms total)
[  PASSED  ] 19 tests.

**Comment by 95-martin-orion** [comment]
Thanks for the logs! The tests are passing for me as well, so I think we can move ahead with merging this.

**Review by 95-martin-orion — APPROVED** [review]

**Pull request merged**
