### PR TITLE
Update `cibuildwheel` version

### PR DESCRIPTION
**Pull request by vtomole**
See https://github.com/quantumlib/qsim/pull/609#issuecomment-1533660555

### CODE REVIEW

**Comment by 95-martin-orion** [comment]
To remind myself: we should be able to view the generated wheels in the `Build all wheels for testing` logs to confirm that this does what we need it to do.

**Comment by 95-martin-orion** [comment]
From the error logs, it looks like we also need to update our pybind version. `pybind11==2.10.1` is the first version with python 3.11 support ([docs](https://pybind11.readthedocs.io/en/stable/changelog.html#version-2-10-1-oct-31-2022)), and we set the version [here](https://github.com/quantumlib/qsim/blob/30695ff8a26e817594822bd5beccbfe8a62e41dd/pybind_interface/GetPybind11.cmake#L3).

**Comment by vtomole** [comment]
Updated to minimum pybind version to `2.10.1`.

**Comment by vtomole** [comment]
@95-martin-orion Looks like this PR generates a `qsimcirq-0.16.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl`. Will we need to cut a new release once this is in?

**Comment by 95-martin-orion** [comment]
> @95-martin-orion Looks like this PR generates a `qsimcirq-0.16.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl`. Will we need to cut a new release once this is in?

Yup, same as before. All PRs generate wheels - and in theory you could use them, if sufficiently motivated - but they aren't included in `pip install qsimcirq` until they're built into a release.

**Review by 95-martin-orion — APPROVED** [review]

**Comment by vtomole** [comment]
@95-martin-orion No, thank you :smile_cat:

**Pull request merged**
