### PR TITLE
Allow installing for Python 3.12

### PR DESCRIPTION
**Pull request by basnijholt**
I have tested qsim on Python 3.12 and everything works just fine.

### CODE REVIEW

**Comment by NoureldinYosri** [comment]
@basnijholt is this ready for review?

**Comment by basnijholt** [comment]
Yes 👍 

Just FYI on conda-forge we're building for Python 3.12 and CUDA already: https://github.com/conda-forge/qsimcirq-feedstock

**Review by NoureldinYosri — APPROVED** [review]

**Comment by vtomole** [comment]
Hey @NoureldinYosri :) 

When will this be deployed?

**Comment by NoureldinYosri** [comment]
@vtomole I will cut a new minor release after the fixes to cuda build (https://github.com/quantumlib/qsim/pull/645 and https://github.com/quantumlib/qsim/pull/652) are merged.

In the meantime you could try `pip install git+https://github.com/quantumlib/qsim`

**Comment by vtomole** [comment]
Sounds good. Thanks!

**Pull request merged**
