### PR TITLE
add macos11 wheels

### PR DESCRIPTION
**Pull request by laurynasas**
Addresses issue mentioned in https://github.com/quantumlib/qsim/issues/380

### CODE REVIEW

**Comment by laurynasas** [comment]
This is actually not needed as cibuildwheel MacOS wheel supports MacOS 10.9+ https://github.com/pypa/cibuildwheel#what-does-it-do

**Comment by 95-martin-orion** [comment]
> This is actually not needed as cibuildwheel MacOS wheel supports MacOS 10.9+ https://github.com/pypa/cibuildwheel#what-does-it-do

Do we have a way to confirm that this means (10.9)+ and not 10.(9+)?

**Comment by laurynasas** [comment]
> > This is actually not needed as cibuildwheel MacOS wheel supports MacOS 10.9+ https://github.com/pypa/cibuildwheel#what-does-it-do
> 
> Do we have a way to confirm that this means (10.9)+ and not 10.(9+)?

I attempted that locally on my Big Sur machine by successfully installing 10.9 wheel and running the qsimcirq tests. Should we look into automated tests on macos-11 machines? Any other suggestions?

**Comment by 95-martin-orion** [comment]
As long as you were able to confirm it locally, I think the existing test cases will be sufficient. Thanks for verifying!

**Pull request closed without merging**
