### PR TITLE
Update _book.yaml to point to /reference/cc/qsim

### PR DESCRIPTION
**Pull request by yashk2810**

### CODE REVIEW

**Comment by yashk2810** [comment]
@95-martin-orion @lamberta

**Comment by 95-martin-orion** [comment]
What is the interaction between this and #187? Is there additional work required to enable the Python docs?

**Comment by yashk2810** [comment]
For Python API docs, there is a bug that's waiting on your reply. After that we can enable the python API docs.

**Comment by 95-martin-orion** [comment]
> For Python API docs, there is a bug that's waiting on your reply. After that we can enable the python API docs.

Commented there - the PR mentioned in the bug was #187, which has been merged.

**Comment by yashk2810** [comment]
Okay -- @lamberta will setup the python stuff, but this change is orthogonal to python api docs.

**Review by 95-martin-orion — APPROVED** [review]
I guess this is a temporary patch until the Python docs are fully enabled?

**Comment by yashk2810** [comment]
The commented out part is a patch.

THe _doxygen.yaml yaml is not. That's permanent.

**Comment by yashk2810** [comment]
@lamberta is going to fix this with the Python and C++ changes. Closing this PR.

**Pull request closed without merging**
