### PR TITLE
Add Cirq channels.

### LINKED ISSUE #288: Ensure 1:1 parity with Cirq channels
In order to make life easier for qsimcirq translations and TFQ translations, would it be possible to implement kraus operators / channels that have one to one functionality with Cirq ?

In python I can just do something like:

```python3
noisy_op = cirq.depolarize(0.001)(qubit)
```
and then place it inside of my circuit.

In qsim I can construct channels and kraus ops but it looks like I have to do things kind of by hand with "custom" gates. It would be nice to instead just do:

```C++
auto noisy_op = Depolarizing<>::Create(...)
```
Much like we do with Cirq's gates in `cirq_gates.h`.

### PR DESCRIPTION
**Pull request by sergeisakov**
Closes #288

### CODE REVIEW

**Review by MichaelBroughton — APPROVED** [review]
Looks great! Thx so much!

**Comment by 95-martin-orion** [comment]
Happy to defer to Michael on the review here, since I didn't see any issues in a quick pass. One question, though: is there any incentive to update qsimcirq to also use these new channel types?

**Comment by sergeisakov** [comment]
> Happy to defer to Michael on the review here, since I didn't see any issues in a quick pass. One question, though: is there any incentive to update qsimcirq to also use these new channel types?

Yes, we can update qsimcirq to use these new channel types. We have a number of predefined gates and custom matrix gates in qsimcirq. Similarly, we can have a number of predefined channels and custom channels.

**Comment by 95-martin-orion** [comment]
> Yes, we can update qsimcirq to use these new channel types.

Is there any benefit to doing this, outside of readability? e.g. is performance better when using these channel types vs. just using the raw matrix-based Channels like we currently do in qsimcirq?

**Comment by sergeisakov** [comment]
> Is there any benefit to doing this, outside of readability? e.g. is performance better when using these channel types vs. just using the raw matrix-based Channels like we currently do in qsimcirq?

There is no need to calculate SVD explicitly for each channel. This is probably the only benefit, outside of readability.

**Pull request merged**
